# **Numpy Basics**

In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3])

In [0]:
print(a)
print(a.shape)
print(type(a))

In [0]:
b = np.array([1.1,2.2,3.3])

In [7]:
print(b)       
print(b.shape) 
print(type(b))

[1.1 2.2 3.3]
(3,)
<class 'numpy.ndarray'>


In [8]:
print(a[0])       
print(b[2])       
print(type(a[2])) 
print(type(b[1]))

1
3.3
<class 'numpy.int64'>
<class 'numpy.float64'>


In [0]:
c = np.array([[1,2],[3,4]])

In [10]:
print(c)
print(c.shape)

[[1 2]
 [3 4]]
(2, 2)


# **Ones and Zeros**

In [0]:
d = np.ones((2,2))

In [0]:
print(d)            
print(d.shape)       
print(type(d))       
print(type(d[0][0]))

In [0]:
e = np.zeros((3,3))

In [15]:
print(e)             
print(e.shape)       
print(type(e))       
print(type(e[0][0]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [0]:
f = np.random.random((2,2))

In [0]:
print(f)        
print(f.shape)

# **Array Math**

In [19]:
add = a + b
print ("addition")
print(a)
print(b)
print(add)
print(np.add(a,b))

addition
[1 2 3]
[1.1 2.2 3.3]
[2.1 4.2 6.3]
[2.1 4.2 6.3]


In [20]:
sub = a - b
print ("subtraction")
print(sub)               
print(np.subtract(a,b)) 

subtraction
[-0.1 -0.2 -0.3]
[-0.1 -0.2 -0.3]


In [21]:
mul = a * b
print ("multiplication")
print(mul)                
print(np.multiply(a,b)) 

multiplication
[1.1 4.4 9.9]
[1.1 4.4 9.9]


In [22]:
div = a / b
print ("division")
print(div) 
print(np.divide(a,b))   

division
[0.90909091 0.90909091 0.90909091]
[0.90909091 0.90909091 0.90909091]


# **Array Concat**

In [0]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [0]:
print(v1.shape)
print(v2.shape)  

In [0]:
concat = np.concatenate((v1, v2))  

In [0]:
print(concat)      
print(concat.shape) 

In [0]:
v3 = np.array([[1,2,3],[4,5,6]])
v4 = np.array([[40,40,40],[50,50,50]])

In [0]:
print(v3.shape)     
print(v4.shape) 

In [0]:
concat_0 = np.concatenate((v3, v4), axis=0)
concat_1 = np.concatenate((v3, v4), axis=1)
print(concat_0)
print(concat_1)


In [0]:
v_stack  = np.vstack((v3,v4))
h_stack  = np.hstack((v3,v4))
print(v_stack)
print(h_stack)

In [0]:
print(concat_0) 
print(v_stack) 
print(concat_0.shape)

In [0]:
print(concat_1)        
print(h_stack)         
print(concat_1.shape)

# **Array Reshape**

In [0]:
a = np.array([[1,1,1],[2,2,2]])

In [0]:
print(a)
print(a.shape)

In [0]:
b = np.reshape(a, 6)

In [0]:
print(b)
print(b.shape)

In [0]:
c = np.reshape(b, (2,2))

In [0]:
print(c)              
print(c.shape) 

In [0]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [0]:
print(c)        
print(c.shape) 

In [0]:
d = np.ravel(c) # returns contiguous flattened array (1D)
e = c.flatten()

In [0]:
print(d) 
print(e)    

In [0]:
print(np.ravel(c, order='F'))  # Column Major
print(np.ravel(c, order='C'))  # Row Major

# **Expand Dimensions**

In [0]:
a = np.array([500,200,100])

In [0]:
# insert a new axis along the row
b = np.expand_dims(a, axis=0)  

# insert a new axis along the column
c = np.expand_dims(a, axis=1)

print(b)            
print(b.shape)     

print(c)           
print(c.shape) 

# **Unique**

In [0]:
m = np.array([1,2,1,1,4])

# get the unique elements and thier indexes
n, indices = np.unique(m, return_index=True)

print(n)        
print(indices)