In [4]:
# NUMPY

# NumPy is a Python library used for working with arrays.
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

import numpy as np

arr = np.array([1,2,3,4,5])
# arr = np.array((1,2,3,4,5))
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]
[1 2 3 4 5]


In [8]:
# NUMPY - ARRAY DIMENSIONS
import numpy as np
arr = np.array(42) # 0-D array
print(arr.ndim)

arr = np.array([1,2,3,4,5]) # 1D array
print(arr.ndim)

arr = np.array([[1,2,3], [4,5,6]]) # 2D array
print(arr.ndim)

arr = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)

0
1
2
3


In [ ]:
# ARRAY INDEXING

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0])

arr = np.array([[1,2,3], [4,5,6]]) # 2D array
print(arr[0,1]) #2nd element on 1st row
print(arr[1,2]) #3rd element on 2nd row
print('Last element from 2nd dim: ', arr[1, -1])


arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2]) # 1st number repr dimension '[[1,2,3],[4,5,6]]' and 2nd repr. index [4,5,6] and 3rd repr. index of [4,5,6]
print(arr[1,1,1])

In [24]:
# ARRAY SLICING

import numpy as np
arr = np.array([1,2,3,4,5,5])  # normal slicing as list slicing
print(arr[0:2])
print(arr[:-1])

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr[1,0:3]) # Doing slicing on 1st index

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) #both the index will return value of index 2

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:3]) #both the index will return value of index [1:3] no matters if it's 0:2 or anything.


[1 2]
[1 2 3 4 5]
[5 6 7]
[3 8]
[[2 3]
 [7 8]]


In [32]:
# ARRAY DATATYPE
import numpy as np

# arr = np.array([1, 2, 3, 4])

# print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S') # Create an array with data type string:

print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4') # Create an array with data type 4 bytes integer

print(arr)
print(arr.dtype)

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
[1.1 2.1 3.1]
float64
[1 2 3]
int32


In [42]:
#ARRAY COPY & VIEW

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
#array copy will create the object and never the share the reference of the arr
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

arr = np.array([1, 2, 3, 4, 5])
#view copy will create the object and sharing the reference of the arr

x = arr.view()
arr[0] = 31
x[4] = 100

print(arr)
print(x)

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) # No base can be viewed here since it's creates the new object
print(y.base) # base of array can be shared here

[42  2  3  4  5]
[1 2 3 4 5]
[ 31   2   3   4 100]
[ 31   2   3   4 100]
None
[1 2 3 4 5]


In [45]:
# ARRAY SHAPE
import numpy as np
arr = np.array([[1, 2, 3, 4,5], [5, 6, 7, 8,5]])

print(arr.shape) # returns (2,5) 2 -dimension 5 -elements


(2, 5)


In [ ]:
# ARRAY RESHAPE
import numpy as np

# Convert the following 1-D array with 12 elements into a 2-D array.

# The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


# Convert the array into a 1D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

In [ ]:
# ARRAY ITERATION
import numpy as np

arr = np.array([1,2,3,4,5]) # 1D ARRAY
arr = np.array([[1,2,3],[4,5,6]]) # 2D ARRAY
for i in arr:
  print(i)

for idx, x in np.ndenumerate(arr):
  print(idx, x)

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3D ARRAY

for x in np.nditer(arr):
  print(x)

In [75]:
# ARRAY JOIN

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.concatenate((arr1,arr2))
print(arr3)


# 2D ARRAY
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

# USING STACK FUNCTION
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2),axis=0)

print(arr)

#USING HSTACK

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

#USING VSTACK

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

# Stacking Along Height (depth) - to stack along height, which is the same as depth.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [88]:
# ARRAY SPLIT
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

# SPLITING THE 2D ARRAY

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1) # or newarr = np.hsplit(arr, 3) - both are same

print(newarr)



[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [105]:
# NUMPY ARRAY SEARCH

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)  # Which means that the value 4 is present at index 3, 5, and 6.

print(x)


arr = np.array([10,11,25,14,85,92,48])

x = np.where(arr%2 == 0) # which returns the eventh positions

print(x)


# SEARCH SORT -
import numpy as np

arr = np.array([4,7,2,3,6,8,9,8,5,2])

x = np.searchsorted(arr, 7) # It'll return the position where the 7 needs to placed from left side iteration

print(x)


arr = np.array([4,7,2,3,6,8,9,8,5,2])

x = np.searchsorted(arr, 7, side='right') # It'll return the position where the 7 needs to placed from left side iteration

print(x)

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6]) # It'll return the position where the [2,4,6] needs to placed from left side iteration ouput:[1,2,3]

print(x)


(array([3, 5, 6]),)
(array([0, 3, 5, 6]),)
5


In [109]:
# ARRAY SORTING

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

arr = np.array([True, False, True])

print(np.sort(arr))

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]


In [110]:
# ARRAY FILTERING

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)



# CREATING THE FILTER ARRAY - EXAMPLE 2

import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

#EXAMPLE 3

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[41 43]


[False False  True  True]
[43 44]
